GET http://localhost:8080/proverbs/1
Accept: application/json

###
GET http://localhost:8080/helloworld/java
Accept: application/json

###

GET http://localhost:8080/helloworld2/java
Accept: application/json

###

### Send POST request with json body
PUT http://localhost:8080/proverbs/100
Content-Type: application/json

{
  "proverb": "content2"
}


### Send POST request with json body
POST http://localhost:8080/proverbs
Content-Type: application/json

{
  "proverb": "content"
}

### Send GET request with json body
GET http://localhost:8080/proverbs/99
Content-Type: application/json


### Send GET request with json body
GET http://localhost:8080/proverbs
Content-Type: application/json

### Send GET request with json body
GET http://localhost:8080/proverbs/random?type=2
Content-Type: application/json

### Send GET request with json body
GET http://localhost:8080/proverbs/custom?text=content&type=8
Content-Type: application/json
